on:
    push: { branches: master }
    workflow_dispatch: 

jobs:
  build: 
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with: { platforms: arm64 }
      - uses: docker/setup-buildx-action@v3
        with: 
          config-inline: |
            [worker.oci]
              max-parallelism = 2
          driver-opts: 
            network=host
      - uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with: 
          context: . 
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: ghcr.io/${{ github.repository }}:latest
